package org.senlatraining.ui.constants;

public enum Titles {
	A_U_T_O_S_E_R_V_I_C_E,
	Root,
	Masters,
	Orders,
	Garages,
	SortMaters,
	SortByAlpabet,
	SortByStatus,
	SortByDateRegistration,
	SortByDateComplete,
	SortByDatePlanStart,
	SortByPrice,
	SortOrders,
	SortExecutableOrders,
	SortOrdersInDateInterval,
	Add,
	Remove,
	Close,
	Revoke,
	Move,
	ShowList,
	ShowSorted,
	ShowListOfOrders,
	ShowListOfExecutableOrders,
	ShowListInInterval,
	ShowOrder,
	ShowAmountOfFreePlacesOnDate
}
